services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock
  db:
    image: pgvector/pgvector:pg18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-mneme}_${ENVIRONMENT:-development} -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data: